export const voyageData = [
  {
    id_activity: 1,
    name_activity: "Traverser la rue en Thailande",
    description:
      "Le Code de la route existe en Thaïlande, même s'il est peu appliqué. C’est sûrement pour cela qu’il s’agit d’un des 3 pays au monde qui connaît le plus d’accidents de la route. les Thaïlandais sont très peu respectueux du Code de la route. Les véhicules sont nombreux et variés sur les chaussées :  Il en résulte une ambiance anarchique, qu'il vous faudra gérer avec sang froid. Les accidents sont fréquents et souvent mortels. Les limites de vitesse, à 50 km/h en ville et 100 km/h en campagne, ne sont pas respectées.",
    age_recommended: "18-70",
    name_guide: "Phoebe Buffay",
    image: "src/assets/images/traverser-route.png",
    country: "Thaïlande",
    city: "Bangkok",
    price: 80,
    dangerosity: 7.8,
    country_id: 18,
    picto: "src/assets/picto/7.8.png",
  },
  {
    id_activity: 2,
    name_activity: "Base Jump pour fêter ses 80 ans",
    description:
      "Vous êtes en quête d'une sensation de liberté ? Coupez tous les liens avec la réalité en sautant dans le vide absolu.",
    age_recommended: "+70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/base_jump.webp",
    country: "Inde",
    city: "Himalaya",
    price: 2500,
    dangerosity: 9.1,
    country_id: 8,
    picto: "src/assets/picto/9.1.png",
  },
  {
    id_activity: 3,
    name_activity: "Nouvel An au mont Everest",
    description:
      "L'ascension de l'Everest s'entreprend essentiellement au printemps, avant la mousson, mais ne vous laissez pas la météo de vous décourager. Passez un Nouvel An inoubliable sur les sommets de la montagne emblématique. Revivez l'aventure du film Everest et faites des photos sur les lieux du tournage du film.",
    age_recommended: "+70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/Everest.png",
    country: "Népal",
    city: "Katmandou",
    price: 3800,
    dangerosity: 9.3,
    country_id: 13,
    picto: "src/assets/picto/9.3.png",
  },
  {
    id_activity: 4,
    name_activity: "Chercher un woofing dans les favelas",
    description:
      "Favela, aussi écrit favéla, désigne les bidonvilles brésiliens, situés sur des terrains occupés illégalement et contrôlés le plus souvent par des trafiquants de drogue qui luttent entre eux pour obtenir les plus vastes territoires, très souvent malsains (marécages, pentes raides des collines), et dont les habitations sont construites avec des matériaux de récupération. Toutefois, il ne faut pas sous-estimer la hospitalité des habitants des ces quartiers. Partez à l'aventure chez des locaux et partagez un moment de convivialité avec eux.",
    age_recommended: "18-70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/Favelas.png",
    country: "Brésil",
    city: "Rio de Janeiro",
    price: 10,
    dangerosity: 8.6,
    country_id: 3,
    picto: "src/assets/picto/8.6.png",
  },
  {
    id_activity: 5,
    name_activity: "Participer à la Gay Pride en Russie",
    description:
      "Malgré les apparences le peuple russe peut montrer une grande ouverture d'esprit. Partagez une ambiance chaleureuse d'un LGBT pride sur l'emblématique place Rouge aux portes de Kremlin.",
    age_recommended: "18-70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/gay-pride.png",
    country: "Russie",
    city: "Moscou",
    price: 250,
    dangerosity: 7.9,
    country_id: 16,
    picto: "src/assets/picto/7.9.png",
  },
  {
    id_activity: 6,
    name_activity:
      "Cueillir de la marijuana dans des exploitations clandestines",
    description:
      "Profitez de la nature et de l'ambiance paisible des exploitations agricoles en Bolivie. Partagez un moment de convivialité avec les autres travailleurs.",
    age_recommended: "18-70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/Canabis.png",
    country: "Bolivie",
    city: "La Paz",
    price: 20,
    dangerosity: 5.8,
    country_id: 2,
    picto: "src/assets/picto/5.8.png",
  },
  {
    id_activity: 7,
    name_activity: "Se désalterer dans le Gange",
    description:
      "Des millions de fidèles trouvent le salut en se baignant dans ses flots et en buvant son eau. Ce fleuve sacré contient les pires poisons : métaux lourds, matières fécales et produits chimiques intoxiquent lentement mais sûrement ses pèlerins.",
    age_recommended: "18-70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/eau-gange.png",
    country: "Inde",
    city: "New Delhi",
    price: 15,
    dangerosity: 7.1,
    country_id: 8,
    picto: "src/assets/picto/7.1.png",
  },
  {
    id_activity: 8,
    name_activity: "Marcher en déambulateur sur la piste cyclable à Amsterdam",
    description:
      "Il y a 400 km de pistes cyclables dans Amsterdam , on a le droit de prendre les rues à contre-sens, traverser les parcs à vélo et les feux sont réglés de manière à donner la priorité au vélos. D'ailleurs la règle est simple : les vélos ont toujours priorité – ici les cyclistes règnent en maître sur la ville. Tentez le défi de vous balader sur la piste cyclable tout en prenant votre temps.",
    age_recommended: "+70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/Velo-Amsterdam.png",
    country: "Pays-Bas",
    city: "Amsterdam",
    price: 50,
    dangerosity: 7.3,
    country_id: 14,
    picto: "src/assets/picto/7.3.png",
  },
  {
    id_activity: 9,
    name_activity: "Courses de buffles d'eau",
    description:
      "Tous les ans à Chonburi, dans l’Est de la Thaïlande, se célèbre une compétition pour rendre hommage aux buffles et exprimer une grande gratitude à ces animaux qui travaillent pour les agriculteurs tout au long de l’année. Assistez à ces courses rapides, impressionnantes et franchement dangereuses!",
    age_recommended: "+70",
    name_guide: "Luna Lovegood",
    image: "src/assets/images/course-buffalo.png",
    country: "Thaïlande",
    city: "Chonburi",
    price: 300,
    dangerosity: 7.5,
    country_id: 18,
    picto: "src/assets/picto/7.5.png",
  },
  {
    id_activity: 10,
    name_activity: "Marathon des Sables",
    description:
      "Se déroulant à chaque année au mois d’avril, ce marathon prenant place dans le Sud du Maroc est une course d’environ 240 kilomètres pendant laquelle les participants doivent porter sur leur dos la nourriture suffisante pour une semaine. Une épreuve sportive extrêmement difficile qui se déroule dans la chaleur du désert, sous des températures extrêmes pouvant avoisiner les 50 degrés.",
    age_recommended: "+70",
    name_guide: "Michael Scott",
    image: "src/assets/images/MarathonDesSables.png",
    country: "Maroc",
    city: "Casablanca",
    price: 180,
    dangerosity: 7.3,
    country_id: 11,
    picto: "src/assets/picto/7.3.png",
  },
  {
    id_activity: 11,
    name_activity: "Monter la tour Burj Khalifa à pied",
    description:
      "Vous n'êtes pas sportif et vous êtes claustrophobe ? Ce n'est pas grave ! Vivez une expérience inédite d'arriver au sommet de la plus grande tour du Monde à pied.  ",
    age_recommended: "+70",
    name_guide: "Michael Scott",
    image: "src/assets/images/burj-kalifa.png",
    country: "Émirats Arabe Unis",
    city: "Dubaï",
    price: 125,
    dangerosity: 7.0,
    country_id: 5,
    picto: "src/assets/picto/7.0.png",
  },
  {
    id_activity: 12,
    name_activity: "Monter El Capitan sans corde",
    description:
      "Aujourd'hui c'est El Capitan, roi de la vallée qui apparaît en fond d'écran par défaut lorsqu'ils ouvrent leur Mac. La falaise de 1 200 m dépourvue de fissures est l'un des plus fameux spots de grimpe au monde avec des routes qui durent de 2 à 7 jours. Allez au-delà de vos peurs et monter la falaise sans protection.",
    age_recommended: "18-70",
    name_guide: "Michael Scott",
    image: "src/assets/images/El-Capitan.png",
    country: "USA",
    city: "Parc National Yosemite",
    price: 250,
    dangerosity: 8.5,
    country_id: 19,
    picto: "src/assets/picto/8.5.png",
  },
  {
    id_activity: 13,
    name_activity: "Nourrir une murène aux antilles",
    description:
      "Vous êtes passionnés (ou pas) par le monde sous-marin ? Vivez un moment de complicité avec les murènes en les donnant à manger.",
    age_recommended: "18-70",
    name_guide: "Michael Scott",
    image: "src/assets/images/Murene.png",
    country: "Tahiti",
    city: "Rangiroa",
    price: 150,
    dangerosity: 8.7,
    country_id: 17,
    picto: "src/assets/picto/8.7.png",
  },
  {
    id_activity: 14,
    name_activity: "Faire un safari à pied",
    description:
      "Vous avez marre d'être enfermé dans une voiture en voyant les animaux quelque part au loin ...? Nous aussi ! C'est pour cela qu'on vous propose le premier safari au monde à pied. Vous verrez les animaux de près et peut-être que vous pourrez même les carresser.",
    age_recommended: "+70",
    name_guide: "Michael Scott",
    image: "src/assets/images/Safari.jpeg",
    country: "Namibie",
    city: "Windhoek",
    price: 300,
    dangerosity: 8.7,
    country_id: 12,
    picto: "src/assets/picto/8.7.png",
  },
  {
    id_activity: 15,
    name_activity: "Monter son premier site sans boucle infinie",
    description:
      "Vers l'infini et au delà a dit Buzz l'éclair en faisant tomber sa base de données externe. Ne faites pas la même erreur que lui et montez votre premier site sans tuto et sans formateur.",
    age_recommended: "18-70",
    name_guide: "Michael Scott",
    image: "src/assets/images/boucle_infinie.webp",
    country: "France",
    city: "Bordeaux",
    price: 7500,
    dangerosity: 10,
    country_id: 7,
    picto: "src/assets/picto/10.png",
  },
  {
    id_activity: 16,
    name_activity: "Faire de la high-line entre deux montgolfières",
    description:
      "Vivez une expérience vertigineuse en marchant sur la high-line entre deux montgolfières. Tout ce qu'il faut c'est un peu d'équilibre et un testament à jour.",
    age_recommended: "+70",
    name_guide: "Michael Scott",
    image: "src/assets/images/high-line.png",
    country: "Brésil",
    city: "São Paulo",
    price: 2250,
    dangerosity: 9.0,
    country_id: 3,
    picto: "src/assets/picto/9.png",
  },
  {
    id_activity: 17,
    name_activity: "Tenter de battre le record de Jacques Mayol en Apnée",
    description:
      "Vous avez aimé le film Le Grand Bleu ? Nous pouvons vous faire revivre les emotions de Jacques Mayol ! Tentez de battre son record afin que votre nom reste dans l'histoire. Prérequis nécessaire ? Aucun !",
    age_recommended: "+70",
    name_guide: "Ron Swanson",
    image: "src/assets/images/apnee.webp",
    country: "Italie",
    city: "Ile d'Elbe",
    price: 5130,
    dangerosity: 9.1,
    country_id: 9,
    picto: "src/assets/picto/9.1.png",
  },
  {
    id_activity: 18,
    name_activity: "Rodéo après une bouteille de tequila",
    description:
      "Combinez les activités les plus emblématiques de la région : tequila et rodeo. Parfait pour un enterrement de vie de garçon ou un enterrement tout court.",
    age_recommended: "18-70",
    name_guide: "Phoebe Buffay",
    image: "src/assets/images/Rodéo.png",
    country: "USA",
    city: "Dallas",
    price: 568,
    dangerosity: 8.2,
    country_id: 19,
    picto: "src/assets/picto/8.2.png",
  },
  {
    id_activity: 19,
    name_activity: "Lacher de taureau",
    description:
      "Admirez l'événement le plus emblématique de la ville depuis le premier rang. Nous vous réserverons une table en terasse dans la rue principale de la ville. Vous la reconnaitrez pas sa nappe rouge.",
    age_recommended: "+70",
    name_guide: "Ron Swanson",
    image: "src/assets/images/taureau-Pamplune.png",
    country: "Espagne",
    city: "Pampelune",
    price: 369,
    dangerosity: 8.2,
    country_id: 6,
    picto: "src/assets/picto/8.2.png",
  },
  {
    id_activity: 20,
    name_activity: "Attendre au feu rouge au Vietnam",
    description:
      "Les Thaïlandais sont très peu respectueux du Code de la route. Les véhicules sont nombreux et variés sur les chaussées :  Il en résulte une ambiance anarchique, qu'il vous faudra gérer avec sang froid. Les accidents sont fréquents et souvent mortels. Ca vous a donné envie ? Parfait !",
    age_recommended: "18-70",
    name_guide: "Ron Swanson",
    image: "src/assets/images/Feu-rouge.png",
    country: "Vietnam",
    city: "Ho Chi Minh",
    price: 10,
    dangerosity: 7.2,
    country_id: 20,
    picto: "src/assets/picto/7.2.png",
  },
  {
    id_activity: 21,
    name_activity: "Répondre Oui à une question incomprise, en Asie",
    description:
      "Vous vous sentez seul(e) et vous avez envie de faire de nouvelles connaissance ? Parlez aux locaux, faites-vous inviter chez eux, vous ne le regretterez pas, promis.",
    age_recommended: "18-70",
    name_guide: "Ron Swanson",
    image: "src/assets/images/Oui-Asiatique.png",
    country: "Cambodge",
    city: "Phnom Penh",
    price: 30,
    dangerosity: 6.2,
    country_id: 4,
    picto: "src/assets/picto/6.2.png",
  },
  {
    id_activity: 22,
    name_activity: "Suivre un rabatteur au Japon",
    description:
      "Faites confiance aux locaux pour les expériences les plus inédites. Suivez-les dans leurs bars et attendez voir ce qu'ils ont à vous offrir.",
    age_recommended: "18-70",
    name_guide: "Ron Swanson",
    image: "src/assets/images/Rabateur.png",
    country: "Japon",
    city: "Tokyo",
    price: 150,
    dangerosity: 6.5,
    country_id: 10,
    picto: "src/assets/picto/6.5.png",
  },
  {
    id_activity: 23,
    name_activity: "Nager avec les requins",
    description:
      "Beaucoup sous-estiment l'intelligence et la gentillesse des requins. Ce sont des animaux très attachants et affectueux.",
    age_recommended: "+70",
    name_guide: "Jim Carrey",
    image: "src/assets/images/Requin.png",
    country: "France",
    city: "La Réunion",
    price: 880,
    dangerosity: 8.7,
    country_id: 7,
    picto: "src/assets/picto/8.7.png",
  },
  {
    id_activity: 24,
    name_activity: "Faire du surf sur le Bassin d'Arcachon",
    description:
      "Ne sous-estimez pas les sensations que peut procurer une bonne session de surf sur le Bassin. Testez pas vous-même.",
    age_recommended: "18-70",
    name_guide: "Jim Carrey",
    image: "src/assets/images/Surf-Bassin.png",
    country: "France",
    city: "Bordeaux",
    price: 250,
    dangerosity: 4.7,
    country_id: 7,
    picto: "src/assets/picto/4.7.png",
  },
  {
    id_activity: 25,
    name_activity: "Apprendre le surf à Nazaré",
    description:
      "Le Canyon de Nazaré provoque de grosses vagues, faisant de Nazaré un spot incontournable dans le monde du surf. Actuel détenteur du record du monde de la plus grosse vague surfée avec une hauteur d’un peu plus de 24 mètres à Nazaré en 2017 est Rodrigo Koxa. Niveau : recommandés pour les débutants!",
    age_recommended: "18-70",
    name_guide: "Jim Carrey",
    image: "src/assets/images/Surf-Nazare.png",
    country: "Portugal",
    city: "Nazaré",
    price: 980,
    dangerosity: 8.9,
    country_id: 15,
    picto: "src/assets/picto/8.9.png",
  },
  {
    id_activity: 26,
    name_activity: "Prendre la ligne 13 à Paris à l'heure de pointe",
    description:
      "Vous vous sentez un peu seul(e) ? Venez à la rencontre des gens à l'ambiance Amélie Poulain",
    age_recommended: "18-70",
    name_guide: "Jim Carrey",
    image: "src/assets/images/Ligne13.png",
    country: "France",
    city: "Paris",
    price: 15,
    dangerosity: 7.2,
    country_id: 7,
    picto: "src/assets/picto/7.2.png",
  },
  {
    id_activity: 27,
    name_activity: "Refaire son passeport en 3 jours ",
    description:
      "Envie d'une aventure à la dernière minute dans un pays exotique ? Pas de problème. Faites confiance à l'administration française pour finaliser vos documents dans les plus brefs délais.",
    age_recommended: "18-70",
    name_guide: "Jim Carrey",
    image: "src/assets/images/Passeport.png",
    country: "France",
    city: "Bordeaux",
    price: 75,
    dangerosity: 6.8,
    country_id: 7,
    picto: "src/assets/picto/6.8.png",
  },
  {
    id_activity: 28,
    name_activity: "Vivre avec le SMIC à Bordeaux",
    description:
      "Il en faut peu pour être heureux ! Vivez une vie sans excès, sans plaisir et sans joie de vivre.",
    age_recommended: "18-70",
    name_guide: "Jim Carrey",
    image: "src/assets/images/Smic.png",
    country: "France",
    city: "Bordeaux",
    price: 1645,
    dangerosity: 9.5,
    country_id: 7,
    picto: "src/assets/picto/9.5.png",
  },
  {
    id_activity: 29,
    name_activity: "Marcher sur la Canebière avec un maillot d'équipe de Paris",
    description:
      "On dit que les opposés s'attirent. Testez ce dicton dans le quartier le plus animé de Marseille.",
    age_recommended: "18-70",
    name_guide: "Phoebe Buffay",
    image: "src/assets/images/Foot-cannebiere.png",
    country: "France",
    city: "Marseille",
    price: 50,
    dangerosity: 7.2,
    country_id: 7,
    picto: "src/assets/picto/7.2.png",
  },
  {
    id_activity: 30,
    name_activity:
      "Aller voir un match de La Bombonera avec un maillot de River Plate",
    description:
      "On dit que les opposés s'attirent. Testez ce dicton dans le stade mythique de Bombonera.",
    age_recommended: "18-70",
    name_guide: "Phoebe Buffay",
    image: "src/assets/images/Foot-Bonbonnera.png",
    country: "Argentine",
    city: "Buenos Aires",
    price: 86,
    dangerosity: 7.8,
    country_id: 1,
    picto: "src/assets/picto/7.8.png",
  },
  {
    id_activity: 31,
    name_activity: "Trouver des toilettes publiques propres au centre de Paris",
    description:
      "Tout comme les yeux sont le miroir de l'âme, les toilettes sont le mirroir d'une ville. Relévez le défi de trouver les toilettes publiques qui brillent comme la Ville des Lumières.",
    age_recommended: "18-70",
    name_guide: "Phoebe Buffay",
    image: "src/assets/images/toilettes.png",
    country: "France",
    city: "Paris",
    price: 50,
    dangerosity: 1,
    country_id: 7,
    picto: "src/assets/picto/1.0.png",
  },
  {
    id_activity: 32,
    name_activity: "Manger du fugu",
    description:
      "Vous aimez des sushis ? Vous devez goûter le fugu ! C’est un poisson toxique qui ne peut être servi au Japon que dans les restaurants disposant d’un maître fugu qualifié. Notre maître fugu étant en arrêt maladie, on a fait appel à son stagiaire Jonathan. Ca devrait être tout aussi bon !",
    age_recommended: "18-70",
    name_guide: "Phoebe Buffay",
    image: "src/assets/images/Fugu.png",
    country: "Japon",
    city: "Tokyo",
    price: 250,
    dangerosity: 8.5,
    country_id: 10,
    picto: "src/assets/picto/8.5.png",
  },
  {
    id_activity: 33,
    name_activity: "Découvrir le gout du Durian",
    description:
      "Faites vibrer vos papilles en goûtant un durian. C’est vrai que l’odeur de ce fruit le précède souvent, que ce soit en réputation ou dans vos narines. Ca sent un peu la mort mais il y a des gens qui aiment ça. Peut-être que c'est votre cas également ?",
    age_recommended: "18-70",
    name_guide: "Phoebe Buffay",
    image: "src/assets/images/Durian.png",
    country: "Vietnam",
    city: "Hanoï",
    price: 45,
    dangerosity: 8.5,
    country_id: 20,
    picto: "src/assets/picto/8.5.png",
  },
];
